(
  CREATE_WALLET, DELETE_WALLET, RESTORE_WALLET, 
  SEED_PROCESS, BLOCKHEIGHT_TAKE, ADDRESS_REQUEST, 
  BALANCE, SEND_ADDR, SEND_SUM, SEND_TRANSFER, SEED_REQUEST,
  MAKE_SEND_TRANSACTION, MAKE_SEND_TRANSACTION_PAY_ID
) = range(13)
